### ISSUE TITLE
Insufficent user permission on build

### ISSUE THREAD

**Issue by solkmaaker** [DigitalNoteXDN/DigitalNote-2#59]
Build DigitalNote daemon
`cd ~; cd ~/DigitalNote/src; chmod a+x obj; chmod a+x leveldb/build_detect_platform; chmod a+x secp256k1; chmod a+x leveldb; chmod a+x ~/DigitalNote/src; chmod a+x ~/DigitalNote; make -f makefile.unix USE_UPNP=-; cd ~; cp -r ~/DigitalNote/src/DigitalNoted /usr/local/bin/DigitalNoted;`

Regular user does not have write permissions to /usr/local/bin/ folder
Change last part to `sudo cp -r ~/DigitalNote/src/DigitalNoted /usr/local/bin/DigitalNoted;`

**Comment by IamLupo** [comment]
Patched: https://github.com/IamLupo/DigitalNote-2/commit/e77bf7ffb3718da08effe937ff6e9900874f147a
