### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by solkmaaker** [DigitalNoteXDN/DigitalNote-2#60]
Dependencies (if compiled in Debian 10 system) are missing "qt5-qmake" and "qt5-default"
Without qt5-qmake QT wallet build gives error:
`qmake: could not exec '/usr/lib/qt5/bin/qmake': No such file or directory
make: *** No targets specified and no makefile found.  Stop.
`
And without qt5-default QT wallet build gives:
`Project MESSAGE: Building without UPNP support
sh: 1: /usr/lib/qt5/bin/lrelease: not found
Project ERROR: Unknown module(s) in QT: core gui widgets network printsupport
make: *** No targets specified and no makefile found.  Stop.
`

**Comment by IamLupo** [comment]
This is what i already have fixed in my branch but its not much merged yet
