### ISSUE TITLE
mined froze after update

### ISSUE THREAD

**Issue by Chic-ho** [DigitalNoteXDN/DigitalNote-2#68]
hello , I been mined for very long time with no issue  until after 2.0.0.2 update ..can u give instruction how to unfreeze mined or this normal procedure ?

**Comment by Chic-ho** [comment]
still stuck with new update to mined xdn...not sync

**Comment by IamLupo** [comment]
Open the qt wallet v2.0.0.2 and go to "Help > Open data dir".

!!!First make a backup of your wallet.dat!!!

Close the qt wallet.

Now remove all files inside this folder and copy over your wallet.dat in there.

Start the qt wallet again. And you will see it will sync again. After this process is been done.

Go to "Help > debug window > Console" and type "repairwallet".

Restart your qt wallet again and your good to go!

PS: Never run a old version anymore. This can corrupt your blockchain and you have to resync it again with the method above.

Good luck!

XDN Team

**Comment by Chic-ho** [comment]
HELLO XDN  TEAM, hard time understanding what you are saying . qt wallets
got me confuse ! which i used other one ..this what i did, copy wallet.dat
into new  backup folder then deleted old files then download 403438 and
pasted into  wallet.dat into backup folder as well...then download 2.0.0.2
wallet...it's syncing now 2 years and 15 weeks. hope this makes sense
...lets you know after sync if succeed or not ...thank again

bittrex still on maintenance can't send to my wallet .Will it be fixed ?

**Comment by rubber-duckie-au** [comment]
Hi Chic-ho, you need to extract the 403438.zip into XDN folder, so take a backup of wallet.dat file again and delete everything in XDN folder. After you do extract of 403438.zip and copy wallet.dat back in you should have 2 files and 3 folders:

- blocks folder
- database folder
- txleveldb folder
- blk0001.dat file
- wallet.dat file

Then open 2.0.0.2 wallet again and everything should be ok. If not we have community support on Discord https://discord.gg/McGyHFtk8U

**Comment by Chic-ho** [comment]
I have issue... rubber-duckie-au...after complete sync .cant unlock with same seed phrase...i dont want to change it seeds then i'll lost xdn right ?..

**Comment by Chic-ho** [comment]
hello rubber0duckie-au... im stuck at ERROR ..loading block database .. I restarted over again deleted xdn wallet re upload . after I shut my computer and restarted...this what I have is error..loading block database... I couldn't find wallet.dat to paste in 403438.zip... sorry for bothering you  trying get this going ... i did got on discord..dont know what im looking for

**Comment by rubber-duckie-au** [comment]
Does the wallet show your coins before unlock? is it the same wallet? Replace wallet.dat with a backup and make sure you have same wallet. XDN uses password and the update would not effect your password or coins.

**Comment by Chic-ho** [comment]
no the wallet did not show my mil coins, yes same wallet logo ... thats problem I couldn't find wallet backup. just zip gone ...

**Comment by Chic-ho** [comment]
right now i just have error  says loading block database

**Comment by rubber-duckie-au** [comment]
The wallet.dat file is your wallet. If you did not copy your wallet into XDN folder it will create a empty new one. Then you need to close wallet. locate wallet.dat in XDN folder and rename it to wallet.old. Then you must copy your wallet.dat from your backup into this folder. 
Restart wallet and your coins should show up. If you don't have a backup copy of your wallet the check Recycle Bin on your PC for a copy you may have deleted.

**Comment by Chic-ho** [comment]
okay try again look for wallet.. thanks for replying 

![Screenshot 2021-07-31 15 49 02](https://user-images.githubusercontent.com/88128143/127754168-979ad6c4-4715-4ac5-87a3-4b1cbd0e8ebd.png)

**Comment by Chic-ho** [comment]
nope cant find wallet this means im screwed?

**Comment by rubber-duckie-au** [comment]
rename your AppData\Roaming\XDN folder to XDN_OLD and open wallet, dont worry about bootstrap, just wait fir it to sync.

whilst waiting do a file search on your whole pc for wallet.dat ... you may have a backup somewhere... that is not in the new XDN folder

**Comment by Chic-ho** [comment]
found wallet doing the search wallet.dat . its in Microsoft folder don't asking why lol...when i open or save have no idea where it go's.. u asking me to redownload xdn again 2.0.0.2? keep rename xdn old in place ? want say i appreciate u helping me on this !  thank you 

![Screenshot 2021-07-31 16 30 42](https://user-images.githubusercontent.com/88128143/127754673-c8e968e6-46e1-4182-9753-c0ff1ca0e6e7.png)
 ..im must so retarted ! shhhh don't tell anybody lol

**Comment by Chic-ho** [comment]
redownload new xdn...still same results.. error .... loading block database.. im gonna take break ..you have good weekend.. thank you for trying helping me out !

**Comment by Chic-ho** [comment]
just remember that I screen shot wallet.dat before putting in new folder ...well that work just type in all wallet.dat in order?

**Comment by rubber-duckie-au** [comment]
As long as that is your old wallet, then it must be renamed to wallet.dat and put in new folder

**Comment by Chic-ho** [comment]
yes my old wallet. thanks

**Comment by Chic-ho** [comment]
looks like I have to be a programmer write wallet.dat.. didn't work for me, still same error.. its 12 wallets .dat

**Comment by rubber-duckie-au** [comment]
ok i dont understand what you are trying to do. 

1. Go Start Menu and type in "show file extensions"
2.  next to "change settings to show file extensions" click "Show Settings"
3. UNTICK "Hide extensions for known file types" and click OK
4. now you must rename your wallet to wallet.dat
5. Open File Explorer type %appdata%/XDN into address bar
6. delete everything in that folder and put your wallet.dat in there
7. Open wallet

**Comment by Chic-ho** [comment]
okay im in wallet ..it back to sync 2yrs and 25 weeks. thank u! keep u up to date on monday..u need to enjoy ur weekend . thanks again.

**Comment by Chic-ho** [comment]
goodmorning rubber-duckie... didnt sync stuck at 2years and 5 weeks
![Screenshot 2021-08-01 21 04 45](https://user-images.githubusercontent.com/88128143/127905443-233258bd-f726-4fc9-8aa9-5eb91512fc02.png)

**Comment by Chic-ho** [comment]
how am i gonna get back my xdn ? nothing seems to be working for me .. I suck am not computer svy !

**Comment by Chic-ho** [comment]
hello rubber -duckie ... wondering leaving old xdn wallets causing my new 2.0.0.2 wallet not syncing ??

**Comment by Chic-ho** [comment]
have no problem deleting old siacoin SIA, daedalus ADA   upload new wallets then put in my seed phrase.. wouldnt XDN wallet work that way ?? i appreciate ur help thanks !

**Comment by rubber-duckie-au** [comment]
We did a hard fork, which requires a resync. Not sure why it's not working
for you. No one else has reported this issue. Can you show me what is in
your XDN folder where your wallet.dat file is?

**Comment by Chic-ho** [comment]
![Screenshot 2021-08-02 18 45 34](https://user-images.githubusercontent.com/88128143/127944946-9bfbede2-7b4c-40e1-8eed-62d00df9f14d.png)

**Comment by rubber-duckie-au** [comment]
Ok there is your issue, the files and folders on the screen are in a folder called 403438.. this is not where they should be. 
1. Select all these files and folder, right click mouse and select COPY
2,. Open another file explorer and type %appdata%/XDN (as shown below) and hit enter.
3. Delete everything out of this folder EXCEPT the backups folder
4. Right click and paste in what you copied from step 1.
5. Open wallet, all should be fine if you follow these steps exactly

![image](https://user-images.githubusercontent.com/53319864/127948211-1254ad4f-941d-4b58-aae5-7c58b82ddd05.png)

**Comment by Chic-ho** [comment]
want me to delete all of them and keep  backup? and copy and paste 403438 files in this folder ?

![Screenshot 2021-08-02 19 35 40](https://user-images.githubusercontent.com/88128143/127948951-d0784708-0245-4408-aada-b02d96047933.png)

**Comment by rubber-duckie-au** [comment]
yes that should work

**Comment by Chic-ho** [comment]
okay. thanks rubber-duckie. let you know in few days if good or bad news..am nervous as hell !

**Comment by stunnaxdn** [comment]
Please join our discord for help/support unfortunately this is not a means
of support. As everyone following our GitHub is getting your
troubleshooting notifications! Kindly join our discord for further help
https://discord.gg/FamKBx2

**Comment by Chic-ho** [comment]
oh really ! thats nice ! lol

**Comment by Chic-ho** [comment]
okay this what I have after copy and paste. 1st pop up after enter and 2nd screenshot when i type %appdata%. kinda confused will they both follow thru when uploading new xdn wallet
![Screenshot 2021-08-02 19 58 45](https://user-images.githubusercontent.com/88128143/127951690-49829638-29ac-4048-8690-b19c6b42f4cb.png)
 
![Screenshot 2021-08-02 20 00 12](https://user-images.githubusercontent.com/88128143/127951743-1b50a1b4-c3b6-4d3e-b683-cee611a830f9.png)

**Comment by Chic-ho** [comment]
wallets went thru ..but am missing 72,119 xdn before mined xdn started on 25th... can you fix this ?

**Comment by rubber-duckie-au** [comment]
in wallet:
1. Open Help Menu
2. Select Debug Window
3. click Console tab
4. type: repairwallet

**Comment by Chic-ho** [comment]
yes , i did that still same low amount

**Comment by rubber-duckie-au** [comment]
what was the output of that command? if it shows a coin amount in the output then restart wallet.

**Comment by Chic-ho** [comment]
what you mean output after I type repairwallet , just say "wallet check passed , true "

![Screenshot 2021-08-02 21 01 00](https://user-images.githubusercontent.com/88128143/127955731-f9a9b9e8-0808-4ed3-98d2-41c6cac3628a.png)

**Comment by stunnaxdn** [comment]
Try restarting your pc now

**Comment by Chic-ho** [comment]
ok

**Comment by Chic-ho** [comment]
wallet still same low  amount.. heres screenshot just before but havent collect mined at all..as you can see missing between 7-01-21 thru 7-27-21... 
![Screenshot 2021-08-02 21 26 03](https://user-images.githubusercontent.com/88128143/127957617-979622d9-cbbc-48d8-8526-da07e6c28f39.png)


![Screenshot 2021-07-28 08 01 14](https://user-images.githubusercontent.com/88128143/127957351-2bab2896-936b-4366-8d2c-2e097bd3453c.png)

**Comment by rubber-duckie-au** [comment]
please email me at rubberduckie.au@gmail.com, your wallet is working. Further investigations of funds cannot occur on GitHub

**Comment by Chic-ho** [comment]
okay .am chatting with arc phoenix..im close that discord

**Comment by Chic-ho** [comment]
Sent u email

**Comment by Chic-ho** [comment]
im go bed ..see you in morning its 11;25 pm california

**Comment by Chic-ho** [comment]
goodmorning rubber duckie.. why reddit closed? I say something wrong ?
