### ISSUE TITLE
[COMPILE] Linux Warning Finding Translations Fails to Compile

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [DigitalNoteXDN/DigitalNote-2#69]
Compile fails when running qmake as the readme says to do.
https://github.com/DigitalNoteXDN/DigitalNote-2/tree/v2.0.0.2#build-digitalnote-daemon

Followed all instructions other than swap and berkeleydb install, already done on previous version install.

Warning when using qmake, used both options and output is the same.
`
~/DigitalNote# qmake -qt=qt5 DigitalNote.daemon.pro
Info: creating stash file /pathto/DigitalNote/.qmake.stash
Project MESSAGE: Building without UPNP support
lrelease warning: Met no 'TRANSLATIONS' entry in project file '/pathto/DigitalNote/DigitalNote.daemon.pro'
`

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

**Comment by 2a5A1Ghu1** [comment]
Resolved in discord.

Just run
`make`
after the error

![Screen Shot 2021-08-02 at 12 53 50 AM](https://user-images.githubusercontent.com/13294167/127824402-644c9550-689c-45a2-98b6-00ebb37ee85c.png)

**Comment by IamLupo** [comment]
Its not a error its a warning. This means the process can just continue as normal.

I looked for a solution to supress this warning but there is no documentation about it in qmake.
