### ISSUE TITLE
No GUI

### ISSUE THREAD

**Issue by kozakoff** [DigitalNoteXDN/DigitalNote-2#79]
Release Version 2.0.0.5 on specs below. DigitalNoted.exe runs, no errors, but GUI does not display.

Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Home
Version	21H2
Installed on	‎2/‎23/‎2022
OS build	22000.527
Experience	Windows Feature Experience Pack 1000.22000.527.0

**Comment by kozakoff** [comment]
QT version runs fine

**Comment by IamLupo** [comment]
Digitalnoted.exe is the daemon.  It runs in the background as a services. You can access it with commands.
